### ISSUE TITLE
'objc/objc-block-trampolines.h' file not found

### ISSUE THREAD

**Issue by Yannmm** [ssyzh/objc4-750#1]
/Users/yannmm/Downloads/objc4-750-master/runtime/objc-block-trampolines.mm:38:10: 'objc/objc-block-trampolines.h' file not found

注释掉此行即可

macOS 10.14.1, Xcode 9.4.1

![a](https://ws3.sinaimg.cn/large/006tKfTcly1g196jwpq53j31hi0o645s.jpg)

**Comment by GhostClock** [comment]
nice 👍
